articles/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'articles'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comment_create', views.comment_create, name='comment_create'),
    path('<int:article_pk>/<int:comment_pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),

    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models
from django.core.validators import EmailValidator, MinValueValidator
from django.conf import settings

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    # article.user
    # user.articles
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='articles')

    # article.liked_user.all()
    # user.liked_articles.all()
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_articles')

    class Meta:
        ordering = ('-pk', )


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')

    class Meta:
        ordering = ('-pk', )

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'content',]

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ('article', 'user')

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ArticleForm, CommentForm
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import Article, Comment
from IPython import embed
from django.http import HttpResponse

# Create your views here.

#@login_required(login_url='user/login.html')
@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user_id = request.user.id
            article.save()
            return redirect('articles:detail', article.pk)

        # Article 을 생성해달라고 하는 요청
        
    else: #GET
        # Article 을 생성하기 위한 페이지를 달라고 하는 요청
        form = ArticleForm()

    context = {'form': form}
    return render(request, 'articles/create.html', context)

@require_GET
def index(request):
    articles = Article.objects.all()
    context = {'articles':articles}
    

    return render(request, 'articles/index.html', context)

@require_GET
def detail(request, article_pk):
    # 사용자가 url 에 적어보낸 article_pk를 통해 디테일 페이지를 보여준다.
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comments.all()
    form = CommentForm()
    context = {'article': article, 'comments': comments, 'form': form}

    return render(request, 'articles/detail.html', context)

@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article_pk)
            pass
        
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {'form': form}
    return render(request, 'articles/update.html', context)


# @login_required login페이지에서 nextpage로 보내봣자 get요청이라 post로 막힌다.
@require_POST
def delete(request, article_pk):
    # article_pk에 맞는 article 을 꺼낸다.
    # 삭제한다.
    if request.user.is_authenticated:

        article = get_object_or_404(Article, pk=article_pk)
        if article.user == request.user:
            article.delete()
        else:
            return redirect('articles:detail', article_pk)
    return redirect('articles:index')
    
@login_required    
@require_POST
def comment_create(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # temp.article = article
    form = CommentForm(request.POST)
    if form.is_valid():
        
        comment = form.save(commit=False)
        comment.article_id = article_pk
        comment.user_id = request.user.id
        comment.save()

    return redirect('articles:detail', article_pk)

@require_POST
def comment_delete(request, article_pk, comment_pk):
    
    if request.user.is_authenticated:
        
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
            return redirect('articles:detail', article_pk)
    return HttpResponse('로그인을 하세요', status=401)

def like(request, article_pk):
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)

    if article.liked_users.filter(pk=user.pk).exists():
        user.liked_articles.remove(article)
    else:
        user.liked_articles.add(article)
    print(article.liked_users.all())
    return redirect('articles:detail', article_pk)

def follow(reqeust, article_pk, user_pk):
    # 로그인한 유저가 게시글 유저를 Follow or Unfollow 한다.
    user = reqeust.user
    person = get_object_or_404(get_user_model(), pk=user_pk) # 게시글 주인

    if user in person.followers.all():
        person.followers.remove(user)
    else:
        person.followers.add(user)

    return redirect('articles:detail', article_pk)

articles/templates/articles/_follow.html
<div class="jumbotron text-center text-white bg-dark">
<p class="lead mb-1">작성자 정보</p>
<h1 class="display-4">{{ article.user.username }}</h1>
<hr>
<p class="lead">
팔로잉 : {{ article.user.followings.all | length }} / 
팔로워 : {{ article.user.followers.all | length }}
</p> 
{% if user in article.user.followers.all %}
<a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">
Unfollow
</a>
{% else %}
<a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">
Follow
</a>
{% endif %}

</div>

articles/templates/articles/create.html
{% extends 'base.html' %}
{% block title %} Article::Create
{% endblock title %}

{% block container %}
<form action="{% url 'articles:create' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">생성하기</button>
</form>

{% endblock container %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article::Detail{% endblock title %}
{% block container %}

<hr>
<h2>{{ article.title }}</h2>
<p>{{ article.created_at }}</p>
<p>{{ article.user }}</p>
<hr>
<a href="{% url 'articles:like' article.pk %}">
  {% if user in article.liked_users.all %}
    <i class="fas fa-heart fa-lg"></i>
  {% else %}
    <i class="far fa-heart fa-lg"></i>
  {% endif %}
  
</a>

<span>{{article.liked_users.all | length}}</span>
<p>{{ article.content }}</p>
<hr>
{% if article.user == request.user %}
<a href= {% url 'articles:update' article.pk %}><button>[수정하기]</button></a>
<form action="{% url 'articles:delete' article.pk %}" method='POST'>
{% csrf_token %}
<button>[삭제하기]</button>
</form>
{% endif %}
<form action="{% url 'articles:comment_create' article.pk %}" method='POST'>
{% csrf_token %}
{{ form.as_p }}
<input type="hidden" name="article" value="{{ article.pk }}">
<button type="submit">댓글 작성</button>
</form>
{% for comment in comments %}
<li>{{ comment.content }} {{ comment.user }} {{ comment.created_at }} 
{% if request.user == comment.user %}
<form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
{% csrf_token %}
<button type="submit">[댓글삭제]</button>
</form>
{% endif %}
</li> 
{% empty %}
<p>아직 댓글이 없습니다</p>
{% endfor %}

{% include 'articles/_follow.html' %}
{% endblock container %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% block title %}
Articles::index
{% endblock title %}
{% block container %}
<h1>Article List</h1>
{% if user.is_authenticated %}
<a href={% url 'articles:create' %}>생성하기</a>
{% endif %}
<hr>
{% for article in articles %}

<div>
  <h3>{{ article.pk}}. {{article.title}}</h3>
  <p>작성자: {{ article.user }}</p>
  <a href= {% url 'articles:detail' article.pk %}>[상세보기]</a>
</div>

{% endfor %}
{% endblock container %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% block title %} Article::Update{% endblock title %}

{% block container %}
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">수정하기</button>
</form>

{% endblock container %}