accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

articles/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'articles'
urlpatterns = [
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/comment_create', views.comment_create, name='comment_create'),
    path('<int:article_pk>/<int:comment_pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),

    path('admin/', admin.site.urls),
]

review/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href=" {% static 'bootstrap/css/bootstrap-grid.min.css' %}">
  <script src="https://kit.fontawesome.com/12cfc8965a.js" crossorigin="anonymous"></script>
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container">
  <header>
  
  <h1>저희 페이지에 오신걸 환영합니다.</h1>
  {% if user.is_authenticated %}
  <p>Hello, {{user.username}}</p>
  <a href="{% url 'accounts:update' %}">회원정보 수정</a>
  <a href="{% url 'accounts:logout' %}">로그아웃</a>
  <form action="{% url 'accounts:delete' %}" method='POST'>
  {% csrf_token %}
  <button type="submit">회원탈퇴</button></form>
  {% else %}
  <a href="{% url 'accounts:login' %}">로그인</a>
  <a href="{% url 'accounts:signup' %}">회원가입</a>
  {% endif %}
  <a href={% url 'articles:index' %}>[뒤로가기]</a>
  </header>
  </div>
  <div class="container">
  {% block container %}
  {% endblock container %}
  </div>
  

  <script src="{% static 'bootstrap/js/bootstrap.bundle.min' %}"></script>
</body>
</html>